name: "Unit Tests"
description: "Run unit tests using go"
env:
  GO111MODULE: "on"
  GOPROXY: "https://proxy.golang.org"
runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3.0.2

    - name: Setup Go
      uses: actions/setup-go@v3.1.0
      with:
        go-version-file: "go.mod"
    - name: Test
      shell: bash
      run: go test -race -v ./...
