apiVersion: skaffold/v2beta23
kind: Config
build:
  local:
    useBuildkit: true
  artifacts:
    - image: keptncontrib/unleash-service
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    flags:
      upgrade: ["--reuse-values", "--install"]
    releases:
      - name: unleash-service
        namespace: keptn
        artifactOverrides:
          image: keptncontrib/unleash-service
        imageStrategy:
          helm: { }
        overrides:
          resources:
            limits:
              memory: 512Mi
        chartPath: chart
