---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unleash-service
spec:
  selector:
    matchLabels:
      run: unleash-service
  replicas: 1
  template:
    metadata:
      labels:
        run: unleash-service
    spec:
      serviceAccountName: keptn-default
      containers:
        - name: unleash-service
          image: keptncontrib/unleash-service:0.2.0
          ports:
            - containerPort: 8080
          env:
            - name: EVENTBROKER
              value: 'http://event-broker/keptn'
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
          envFrom:
            - secretRef:
                name: unleash
                optional: true
        - name: distributor
          image: keptn/distributor:0.7.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.>'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
---
apiVersion: v1
kind: Service
metadata:
  name: unleash-service
  labels:
    run: unleash-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: unleash-service
